export const AUTH_REGISTER_SAGA = 'AUTH_REGISTER_SAGA';
export const AUTH_LOGIN_SAGA = 'AUTH_LOGIN_SAGA';
export const AUTH_INIT_SAGA = 'AUTH_INIT_SAGA';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_ERROR_CLEAR = 'AUTH_ERROR_CLEAR';

export const ANILIST_SEARCH_SAGA = 'ANILIST_SEARCH_SAGA';
export const ANILIST_SEARCH = 'ANILIST_SEARCH';
export const ANILIST_SEARCH_NEXT_PAGE = 'ANILIST_SEARCH_NEXT_PAGE';
export const ANILIST_SEARCH_NEXT_PAGE_SAGA = 'ANILIST_SEARCH_NEXT_PAGE_SAGA';
export const ANILIST_LOADING = 'ANILIST_LOADING';
export const ANILIST_CLEAR_SEARCH = 'ANILIST_CLEAR_SEARCH';

export const MANGA_INSERT_SAGA = 'MANGA_INSERT_SAGA';
export const MANGA_LOADING = 'MANGA_LOADING';
export const MANGA_DONE_LOADING = 'MANGA_DONE_LOADING';
export const MANGA_SEARCH_SAGA = 'MANGA_SEARCH_SAGA';
export const MANGA_SEARCH = 'MANGA_SEARCH';
export const MANGA_UPDATE_SAGA = 'MANGA_UPDATE_SAGA';
export const MANGA_UPDATE = 'MANGA_UPDATE';
export const MANGA_CLEAR = 'MANGA_CLEAR';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';